# =============================================================================
# ## Checkmarx Advanced Gitlab Integration 
# ## Comments on merge requests and commits
#
# This script is delivered "as-is" with no Checkmarx support
# Feel free to fork and make your own
# =============================================================================

include:
  - project: 'cxrepositories/cxutilities/cxhelpers'
    ref: master
    file: '.checkmarx-helpers.yml'

stages:
  - test
  - deploy

🤞Checkmarx:
  stage: test
  only:
   - master  
  variables:
    CX_PROJECT_NAME: "CxGitlab"
    CX_TEAM_ID: "CxServer\\SP\\Company\\France\\Engineers\\Legacy-Team\\"
    CX_PRESET: "Checkmarx Default"
    CX_MODE: "CxSAST+CxOSA" # run a CxSAST and CxOSA scan
    #CX_SAST_HIGH: 0 # break the build if 1 high vuln has been found by CxSAST
    #CX_OSA_MEDIUM: 0 # break the build if 1 medium vuln has been found by CxOSA
    CX_CHECK_POLICY: "true" # break the build on one violated policy (CxM&O is required)
    CX_SAST_EXCLUDE_FILES: "*.min.js" # exclude *.min.js files from SAST scan
    CX_EXECUTE_PACKAGE_DEPENDENCY: "true" # install dependencies with maven, npm, nuget if any 
    # please consult CxHelpers repo for better advanced customization
    # https://gitlab.com/cxrepositories/cxutilities/cxhelpers
  extends: .checkmarxCommitTpl

🤞Checkmarx on MR:
  stage: test
  only:
    - merge_request  
  variables:
    CX_PROJECT_NAME: "CxGitlab"
    CX_TEAM_ID: "CxServer\\SP\\Company\\France\\Engineers\\Legacy-Team\\"
    CX_PRESET: "Checkmarx Default"
    CX_MODE: "CxSAST+CxOSA"
    #CX_SAST_HIGH: 0
    #CX_OSA_MEDIUM: 0
    CX_CHECK_POLICY: "true" 
    CX_SAST_EXCLUDE_FILES: "*.min.js"
    CX_EXECUTE_PACKAGE_DEPENDENCY: "true"
    CX_INCREMENTAL_SCAN: "false"
  extends: .checkmarxMergeRequestTpl

Deploy:
  image: alpine
  stage: deploy
  only:
    - "master"  
  script:
    - echo 'Deploy successful'